import { useForm, Controller } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";

import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Button,
  Stack,
} from "@mui/material";

const reportTypes = [
  "Procurement",
  "Vendor",
  "Risk",
  "Compliance",
  "Audit",
];

const schema = yup.object({
  report: yup.string().required("Report Name is required"),

  type: yup.string().required("Report Type is required"),

  generatedBy: yup
    .string()
    .required("Generated By is required"),

  status: yup.string().required("Status is required"),

  date: yup.string().required("Date is required"),
});

export default function ReportDialog({
  open,
  onClose,
  onSave,
}) {
  const {
    control,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),

    defaultValues: {
      report: "",
      type: "",
      generatedBy: "",
      status: "Generated",
      date: "",
    },
  });

  const onSubmit = (data) => {
    onSave({
      id: `REP-${Date.now()}`,
      ...data,
    });

    reset();
    onClose();
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      fullWidth
      maxWidth="sm"
    >
      <DialogTitle>Generate Report</DialogTitle>

      <DialogContent>
        <Stack spacing={2} sx={{ mt: 1 }}>

          <Controller
            name="report"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                label="Report Name"
                fullWidth
                error={!!errors.report}
                helperText={errors.report?.message}
              />
            )}
          />

          <Controller
            name="type"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                select
                label="Report Type"
                fullWidth
                error={!!errors.type}
                helperText={errors.type?.message}
              >
                {reportTypes.map((type) => (
                  <MenuItem
                    key={type}
                    value={type}
                  >
                    {type}
                  </MenuItem>
                ))}
              </TextField>
            )}
          />

          <Controller
            name="generatedBy"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                label="Generated By"
                fullWidth
                error={!!errors.generatedBy}
                helperText={errors.generatedBy?.message}
              />
            )}
          />

          <Controller
            name="status"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                select
                label="Status"
                fullWidth
                error={!!errors.status}
                helperText={errors.status?.message}
              >
                <MenuItem value="Generated">
                  Generated
                </MenuItem>

                <MenuItem value="Pending">
                  Pending
                </MenuItem>
              </TextField>
            )}
          />

          <Controller
            name="date"
            control={control}
            render={({ field }) => (
              <TextField
                {...field}
                type="date"
                label="Date"
                fullWidth
                error={!!errors.date}
                helperText={errors.date?.message}
              />
            )}
          />

        </Stack>
      </DialogContent>

      <DialogActions>
        <Button
          onClick={() => {
            reset();
            onClose();
          }}
        >
          Cancel
        </Button>

        <Button
          variant="contained"
          onClick={handleSubmit(onSubmit)}
        >
          Save
        </Button>
      </DialogActions>
    </Dialog>
  );
}