import {
  useState,
  useEffect,
  useMemo,
  useCallback,
} from "react";

import { useSelector, useDispatch } from "react-redux";

import {
  addReport,
  fetchReports,
} from "../../app/reportSlice";

import {
  Container,
  Typography,
  Snackbar,
  Alert,
  Grid,
  Paper,
  Stack,
  Button,
  Chip,
  Box,
} from "@mui/material";
import FileDownloadIcon from "@mui/icons-material/FileDownload";

import SearchBar from "../../components/reports/SearchBar";
import ReportDialog from "../../components/reports/ReportDialog";
import ReportTable from "../../components/reports/ReportTable";

export default function ReportsPage() {
  const dispatch = useDispatch();

  const {
    reports,
    loading,
  } = useSelector(
    (state) => state.reports
  );

  const [search, setSearch] = useState("");
  const [openDialog, setOpenDialog] = useState(false);
  const [openSnackbar, setOpenSnackbar] = useState(false);
  const [savedReports] = useState([]);

  useEffect(() => {
    dispatch(fetchReports());
  }, [dispatch]);

  const filteredReports = useMemo(() => {
    return reports.filter((report) =>
      `${report.report} ${report.type} ${report.generatedBy}`
        .toLowerCase()
        .includes(search.toLowerCase())
    );
  }, [reports, search]);

  const recentReports = useMemo(() => {
    return reports.slice(0, 3);
  }, [reports]);

  const handleAddReport = useCallback(
    (report) => {
      dispatch(addReport(report));
      setOpenDialog(false);
      setOpenSnackbar(true);
    },
    [dispatch]
  );

  const createCsvContent = (reportsToExport) => {
    const headers = [
      "ID",
      "Report",
      "Type",
      "Generated By",
      "Date",
      "Status",
    ];

    const rows = reportsToExport.map((report) => [
      report.id,
      report.report,
      report.type,
      report.generatedBy,
      report.date,
      report.status,
    ]);

    const escapeCsvValue = (value) => {
      const stringValue = value == null ? "" : String(value);
      const escapedValue = stringValue.replace(/"/g, '""');
      return `"${escapedValue}"`;
    };

    return [
      headers.map(escapeCsvValue).join(","),
      ...rows.map((row) => row.map(escapeCsvValue).join(",")),
    ].join("\n");
  };

  const downloadCsv = (filename, content) => {
    const blob = new Blob(["\uFEFF", content], {
      type: "text/csv;charset=utf-8;",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getReportFilename = (report) => {
    const baseName = report.report || report.type || "Report";
    const shouldAppendReport = !/report$/i.test(baseName.trim());
    const safeName = baseName
      .trim()
      .replace(/\s+/g, "_")
      .replace(/[^a-zA-Z0-9_-]/g, "");

    return shouldAppendReport ? `${safeName}_Report.csv` : `${safeName}.csv`;
  };

  const handleDownloadReport = (report) => {
    const csvContent = createCsvContent([report]);
    downloadCsv(getReportFilename(report), csvContent);
  };

  const handleExportCSV = () => {
    if (filteredReports.length === 0) {
      alert("No reports available to export.");
      return;
    }

    const csvContent = createCsvContent(filteredReports);
    downloadCsv("Reports.csv", csvContent);
  };

  if (loading) {
    return (
      <Container maxWidth="xl">
        <Typography variant="h5">
          Loading Reports...
        </Typography>
      </Container>
    );
  }

  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      <Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ mb: 3, justifyContent: "space-between", alignItems: { xs: "flex-start", md: "center" } }}>
        <Box>
          <Typography variant="h4" fontWeight="bold">
            Reports Center
          </Typography>
          <Typography color="text.secondary">
            Procurement, vendor, risk, and compliance reporting in one place.
          </Typography>
        </Box>
        <Stack direction="row" spacing={1} sx={{ flexWrap: "wrap" }}>
          <Chip label={`${reports.length} Reports`} color="primary" />
          <Chip label={`${savedReports.length} Saved`} color="success" />
        </Stack>
      </Stack>

      {/* Recent Reports Section */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid size={{ xs: 12 }}>
          <Typography variant="h6" sx={{ mb: 2 }}>
            Recent Reports
          </Typography>
          <Stack direction={{ xs: "column", sm: "row" }} spacing={2}>
            {recentReports.map((report) => (
              <Paper
                key={report.id}
                sx={{
                  p: 2,
                  flex: 1,
                  cursor: "pointer",
                  "&:hover": { boxShadow: 3 },
                }}
              >
                <Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "start" }}>
                  <Box>
                    <Typography variant="subtitle2" fontWeight="bold">
                      {report.report}
                    </Typography>
                    <Chip label={report.type} size="small" sx={{ mt: 1 }} />
                  </Box>
                  <Button
                    size="small"
                    startIcon={<FileDownloadIcon />}
                    onClick={() => handleDownloadReport(report)}
                  >
                    Download
                  </Button>
                </Stack>
              </Paper>
            ))}
          </Stack>
        </Grid>
      </Grid>

      {/* Saved Reports Section */}
      {savedReports.length > 0 && (
        <Grid container spacing={3} sx={{ mb: 4 }}>
          <Grid size={{ xs: 12 }}>
            <Typography variant="h6" sx={{ mb: 2 }}>
              Saved Reports ({savedReports.length})
            </Typography>
            <Stack spacing={1}>
              {savedReports.map((report, index) => (
                <Paper key={index} sx={{ p: 2 }}>
                  <Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "center" }}>
                    <div>
                      <Typography variant="body2">{report.report}</Typography>
                      <Typography variant="caption" color="textSecondary">
                        Saved: {report.savedDate}
                      </Typography>
                    </div>
                    <Button
                      size="small"
                      startIcon={<FileDownloadIcon />}
                      onClick={() => handleDownloadReport(report)}
                    >
                      Download
                    </Button>
                  </Stack>
                </Paper>
              ))}
            </Stack>
          </Grid>
        </Grid>
      )}

      <SearchBar
        search={search}
        setSearch={setSearch}
        onAddClick={() => setOpenDialog(true)}
        onExport={handleExportCSV}
      />

      <ReportTable rows={filteredReports} />

      <ReportDialog
        open={openDialog}
        onClose={() => setOpenDialog(false)}
        onSave={handleAddReport}
      />

      <Snackbar
        open={openSnackbar}
        autoHideDuration={3000}
        onClose={() => setOpenSnackbar(false)}
      >
        <Alert
          severity="success"
          variant="filled"
        >
          Report Generated Successfully
        </Alert>
      </Snackbar>

    </Container>
  );
}